name: Deploy Main to Production
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: n1c/laravel-vapor-action@master
          env:
                VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
                COMPOSER_SECRET: ${{ secrets.COMPOSER_SECRET }}
          with:
                args: "deploy production"
